# -*- coding: utf-8 -*-
"""2.1 homework.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rmpFFwYFfdpwc8WevHD0GFLRQLp95_9L
"""

a=str(int(866723090099099099909090909099990))
print(a.count('0'))